"""empty message

Revision ID: c105c5f1f97e
Revises: 9e2f4d212e75
Create Date: 2019-10-26 15:48:38.950032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c105c5f1f97e'
down_revision = '9e2f4d212e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movielist',
    sa.Column('rating', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(length=100), nullable=False),
    sa.Column('is_playable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('types', sa.String(length=100), nullable=False),
    sa.Column('regions', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.String(length=100), nullable=False),
    sa.Column('actor_count', sa.String(length=100), nullable=False),
    sa.Column('vote_count', sa.String(length=100), nullable=False),
    sa.Column('score', sa.String(length=100), nullable=False),
    sa.Column('actors', sa.String(length=100), nullable=False),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movielist')
    # ### end Alembic commands ###
